# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['DEFAULT_VAGRANT_PROVIDER'] = 'libvirt'

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "deb8-base"

  config.vm.provider :libvirt do |libvirt|
    libvirt.host = ""
    libvirt.nested = true
  end

  config.vm.synced_folder ".", "/vagrant", type: "9p"

  config.vm.provision "shell", inline: 
    $script = <<SCRIPT
    echo Shell provisioning...
    sudo rm /etc/apt/apt.conf
    sudo apt-get install puppet -y
SCRIPT

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file = "default.pp"
    puppet.options = '--test'    # see the output
    puppet.synced_folder_type = "9p"
    puppet.facter = {
      "user" => "user",
      "password" => "passwd",
    }
  end
end
